--- drivers/soc/qcom/Makefile
+++ drivers/soc/qcom/Makefile
@@ -95,3 +95,4 @@ obj-$(CONFIG_TRACER_PKT) += tracer_pkt.o
 obj-$(CONFIG_MSM_VSENS) += vsens.o
 obj-$(CONFIG_SERIAL_NUM) += serial_num.o
 obj-$(CONFIG_MSM_HOTPLUG) += msm_hotplug.o
+obj-$(CONFIG_INTELLI_HOTPLUG) += intelli_hotplug.o
